services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Avensome\CommonMarkBundle\:
        resource: '../../*'

    League\CommonMark\Environment:
        factory: ['Avensome\CommonMarkBundle\EnvironmentFactory', 'createEnvironment']

    League\CommonMark\CommonMarkConverter:
        factory: ['Avensome\CommonMarkBundle\ConverterFactory', 'createConverter']

    Aptoma\Twig\Extension\MarkdownEngine\PHPLeagueCommonMarkEngine:
        arguments:
            - '@League\CommonMark\CommonMarkConverter'

    Aptoma\Twig\Extension\MarkdownExtension:
        arguments:
            - '@Aptoma\Twig\Extension\MarkdownEngine\PHPLeagueCommonMarkEngine'
        tags: ['twig.extension']
